apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: subgraph-node
spec:
  prefix: /api/subgraph/
  # rewrite: /subgraphs/name/niftier/composable-contract/graphql
  service: subgraph-node-sidecar-proxy
  resolver: consul-dc1
  tls: ambassador-consul
  load_balancer:
    policy: round_robin
