apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: subgraph-ipfs
  name: subgraph-ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: subgraph-ipfs
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: subgraph-ipfs
    spec:
      containers:
        - image: ipfs/go-ipfs:v0.4.23
          name: subgraph-ipfs
          ports:
            - containerPort: 5001
          resources: {}
          volumeMounts:
            - mountPath: /data/ipfs
              name: subgraph-ipfs
      restartPolicy: Always
      volumes:
        - name: subgraph-ipfs
          persistentVolumeClaim:
            claimName: subgraph-ipfs
status: {}
