apiVersion: v1
kind: ServiceAccount
metadata:
  name: subgraph-node

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subgraph-node
  # namespace: ambassador
  labels:
    service: subgraph-node
spec:
  selector:
    matchLabels:
      service: subgraph-node
  strategy: {}
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service-upstreams: 'subgraph-ipfs:5001,subgraph-postgres:5432'
      labels:
        service: subgraph-node
    spec:
      serviceAccountName: subgraph-node
      containers:
        - name: subgraph-node
          image: graphprotocol/graph-node
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 8000 # GraphiQL / HTTP / GraphQLServer
              hostPort: 8000
            - containerPort: 8001 # Websocket / SubscriptionServer
              hostPort: 8001
            - containerPort: 8020 # Admin JSON-RPC / JsonRpcServer
              hostPort: 8020
            - containerPort: 8030 # Indexing status / IndexNodeServer
              hostPort: 8030
            - containerPort: 8040 # Metrics server
              hostPort: 8040
          envFrom: 
            - configMapRef:
                name: subgraph-node
            - secretRef:
                name: subgraph-node
