apiVersion: v1
kind: Service
metadata:
  name: graph-node
  namespace: ambassador
  annotations:
    a8r.io/owner: adairrr
    a8r.io/description: "A service that encapsulates a graph node"
    a8r.io/repository: "https://github.com/adairrr/niftier/tree/develop/packages/subgraph"
    a8r.io/documentation: "https://github.com/adairrr/niftier/blob/develop/packages/subgraph/README.md"
  labels:
    service: graph-node
spec:
  ports:
    - name: graphql-server
      port: 8000
      targetPort: 8000
    - name: subscription-server
      port: 8001
      targetPort: 8001
    - name: json-rpc-server
      port: 8020
      targetPort: 8020
    - name: index-node-server
      port: 8030
      targetPort: 8030
    - name: metrics-server
      port: 8040
      targetPort: 8040
  selector:
    service: graph-node
status:
  loadBalancer: {}
