apiVersion: v1
kind: Service
metadata:
  name: graphql-stitched
  labels:
    service: graphql-stitched
  annotations:
    a8r.io/owner: adairrr
    a8r.io/description: "A service that exposes a stitched graphql endpoint"
    a8r.io/repository: "https://github.com/adairrr/niftier/tree/develop/packages/stitched-gql-server"
    a8r.io/documentation: "https://github.com/adairrr/niftier/blob/develop/packages/stitched-gql-server/README.md"
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 20000
    # - name: graphql-stitched-endpoint
    #   port: 10000
    #   targetPort: 10000
  selector:
    service: graphql-stitched
