apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceramic-node
  # # namespace: ambassador
  labels:
    service: ceramic-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
