apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subgraph-postgres
  # namespace: ambassador
  labels:
    service: subgraph-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
