apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subgraph-ipfs
  # # namespace: ambassador
  labels:
    service: subgraph-ipfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
