---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: consul-qotm-mapping-tls
spec:
  prefix: /qotm-consul-tls/
  service: qotm-sidecar-proxy
  resolver: consul-dc1
  tls: ambassador-consul
  load_balancer:
    policy: round_robin
